apiVersion: nautilus.phyrone.de/v1alpha1
kind: MinecraftServer
metadata:
  name: lobby
spec:
  replicas: 4
  install:
    software:
      # Install the latest version of purpur (a paper fork)
      purpur: "latest"
  persistence:
    enabled: false