on:
  push: { }
name: Build
jobs:
  build_java:
    name: Build Java
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        name: Setup JDK
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew test
