on:
  push: { }
name: OCI Images
jobs:
  operator:
    name: Build Operator Images
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          github-token: '${{ github.token }}'
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: |-
            ghcr.io/phyrone/nautilus-operator:${{ github.ref_name }}
          file: ./services/operator/Dockerfile
          context: .
          labels: |-
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.timestamp.outputs.timestamp }}

